#+TITLE: README
* Python Interface to ISOTROPY for linux
Preform the various tasks possible with the excellent
ISOTROPY tool in an automated fashion using python.

The software can preform various tasks applying group theoretical methods to the
analysis of crystalline solids.

Obtain the ISOTROPY for linux executable [[https://stokes.byu.edu/iso/isolinux.php][here]].
One should cite "H. T. Stokes, D. M. Hatch, and B. J. Campbell, ISOTROPY Software Suite, iso.byu.edu."
if you use this tool. I am not affiliated with the ISOTROPY authors, but their
tool is being used "under the hood" and they should be credited appropiately.


* As a simple wrapper

When used as a simple wrapper commands can be passed to the isotropy program and
results are parsed in to a list of python dictionaries.

This requires some knowledge of how to use the command line tool itself, but is
the basis for how other functionality is built.

Obtain the possible irreps and their directions involved in a particular
symmetry lowering phase transition:
#+BEGIN_SRC ipython :session :ipyfile :exports :results output drawer :async t :pydir /home/john/.tmp-obpy
import pysotropy as iso

values = {'parent': 221, 'subgroup': 99}
shows = ['irrep', 'direction vector']
with iso.IsotropySession(values, shows) as isos:
    irreps = isos.getDisplayData('ISOTROPY')
print(results)
#+END_SRC

[{'Wyckoff': 'a', 'Point': ['0', '0', '0'], 'Projected Vectors': [['1', '0', '0'], ['0', '1', '0'], ['0', '0', '1']]}, {'Wyckoff': 'b', 'Point': ['1/2', '1/2', '1/2'], 'Projected Vectors': [['1', '0', '0'], ['0', '1', '0'], ['0', '0', '1']]}, {'Wyckoff': 'c', 'Point': [['0', '1/2', '1/2'], ['1/2', '1/2', '0'], ['1/2', '0', '1/2']], 'Projected Vectors': [[['1', '0', '0'], ['0', '0', '0'], ['0', '0', '0']], [['0', '0', '0'], ['0', '0', '0'], ['0', '0', '1']], [['0', '0', '0'], ['0', '1', '0'], ['0', '0', '0']]]}, {'Wyckoff': 'c', 'Point': [['0', '1/2', '1/2'], ['1/2', '1/2', '0'], ['1/2', '0', '1/2']], 'Projected Vectors': [[['0', '0', '0'], ['0', '2', '0'], ['0', '0', '2']], [['2', '0', '0'], ['0', '2', '0'], ['0', '0', '0']], [['2', '0', '0'], ['0', '0', '0'], ['0', '0', '2']]]}]

#+BEGIN_SRC ipython :session :ipyfile :exports :results output drawer :async t :pydir /home/john/.tmp-obpy
values = {'parent': 221,
          'wyckoff': 'a b c',
          'irrep': irreps[0]['Irrep'],
          }
shows = ['basis', 'wyckoff', 'microscopic vector']
with iso.IsotropySession(values, shows) as isos:
    distortion =  isos.getDisplayData('DISTORTION')
for wyck in distortion:
    print(wyck)
#+END_SRC

{'Wyckoff': 'a', 'Point': ['0', '0', '0'], 'Projected Vectors': [['1', '0', '0'], ['0', '1', '0'], ['0', '0', '1']]}
{'Wyckoff': 'b', 'Point': ['1/2', '1/2', '1/2'], 'Projected Vectors': [['1', '0', '0'], ['0', '1', '0'], ['0', '0', '1']]}
{'Wyckoff': 'c', 'Point': [['0', '1/2', '1/2'], ['1/2', '1/2', '0'], ['1/2', '0', '1/2']], 'Projected Vectors': [[['1', '0', '0'], ['0', '0', '0'], ['0', '0', '0']], [['0', '0', '0'], ['0', '0', '0'], ['0', '0', '1']], [['0', '0', '0'], ['0', '1', '0'], ['0', '0', '0']]]}
{'Wyckoff': 'c', 'Point': [['0', '1/2', '1/2'], ['1/2', '1/2', '0'], ['1/2', '0', '1/2']], 'Projected Vectors': [[['0', '0', '0'], ['0', '2', '0'], ['0', '0', '2']], [['2', '0', '0'], ['0', '2', '0'], ['0', '0', '0']], [['2', '0', '0'], ['0', '0', '0'], ['0', '0', '2']]]}


* pysodistort for finding symmetry

Preform the tasks of the isodistort online tool using pymatgen structure
objects, including mode decomposition of the distortion between a high symmetry
and low symmetry crystal.

Very much a work in progress, but has been useful to me already.
